# zfpga flash <sample> [board] -- build the sample and flash it to the SD card
# with the PL bitstream loaded first (so AXI/PL peripherals are alive before
# Zephyr touches them). Generic port of the original scripts/flash.sh daq2.
#
# The PL must be configured before Zephyr's first PL access or the CPU hangs, so
# U-Boot (1) fpga-loads the bitstream, (2) stages zephyr.bin at its link addr,
# (3) jumps with caches off. See profiles/<board>.env for the boot chain.

cmd_flash() {
    [ $# -ge 1 ] || die "usage: zfpga flash <sample> [board]"
    local sample=$1 board=${2:-}
    local sdir="$WS/zephyr/samples/$sample"
    local bdir="$WS/bitstreams/$sample"
    [ -d "$sdir" ] || die "sample not found: $sdir (run 'zfpga new')"
    [ -d "$bdir" ] || die "bitstream folder not found: $bdir (run 'zfpga new')"

    # Board: explicit arg wins, else the marker written by 'zfpga new'.
    [ -z "$board" ] && [ -f "$bdir/.board" ] && board=$(cat "$bdir/.board")
    [ -n "$board" ] || die "no board given and no $bdir/.board marker -- pass it: zfpga flash $sample <board>"

    load_profile "$board"           # BOARD BOOT_CHAIN BIT_LOAD RESET_HINT
    load_bench                      # SD_MUX SD_PART MNT CONSOLE_HINT + board-keyed boot paths
    resolve_bootbin "$board"        # BOOTBIN [UBOOT_IMG] from .flash.local (user build)
    local PRISTINE=${PRISTINE:-auto}

    cd "$WS" || die "cannot cd to workspace $WS"
    local BUILD=build/zephyr
    local XSA="$bdir/system_top.xsa" BIT="$bdir/system_top.bit"
    local ELF="$BUILD/zephyr.elf" BIN="$BUILD/zephyr.bin"

    # --- Build --- (BOARD comes from the sourced profile, not a typo of $board)
    # shellcheck disable=SC2153
    info "building $sdir for $BOARD (pristine=$PRISTINE) ..."
    west build -p "$PRISTINE" -b "$BOARD" -d build "zephyr/samples/$sample"

    # --- PL bitstream: prefer shipped .bit; else extract from the XSA (a zip). ---
    if [ ! -f "$BIT" ] || { [ -f "$XSA" ] && [ "$XSA" -nt "$BIT" ]; }; then
        [ -f "$XSA" ] && { info "extracting system_top.bit from $XSA ..."; \
            unzip -o -j "$XSA" system_top.bit -d "$bdir" >/dev/null; }
    fi

    # --- Preflight: every required file must exist before we touch the card. ---
    local need=("$ELF" "$BIN" "$BOOTBIN" "$BIT")
    [ "$BOOT_CHAIN" = spl ] && need+=("$UBOOT_IMG")
    for f in "${need[@]}"; do
        [ -f "$f" ] || die "required file not found: $f"
    done

    # --- Entry/load addresses straight from the ELF (always match this build). ---
    local READELF; READELF=$(command -v aarch64-zephyr-elf-readelf || command -v readelf || true)
    [ -n "$READELF" ] || die "no readelf found (need readelf or aarch64-zephyr-elf-readelf)"
    local ENTRY LOAD
    ENTRY=$("$READELF" -h "$ELF" | awk '/Entry point/ {print $NF}')
    LOAD=$("$READELF" -l "$ELF" | awk '/LOAD/ {print $4; exit}')     # PhysAddr column
    if [ -z "$ENTRY" ] || [ -z "$LOAD" ]; then die "could not parse ENTRY/LOAD from $ELF"; fi
    info "ELF load = $LOAD, entry = $ENTRY, bit scratch = $BIT_LOAD"

    # --- U-Boot script: load PL, stage Zephyr, jump with caches off. ---
    cat > boot_"$sample".cmd <<EOF
# AUTO-GENERATED by zfpga flash $sample -- do not edit by hand.
echo "Loading $sample bitstream to $BIT_LOAD..."
fatload mmc 0 $BIT_LOAD system.bit
echo "Configuring PL (fpga loadb)..."
fpga loadb 0 $BIT_LOAD \$filesize
echo "Loading Zephyr binary to $LOAD..."
fatload mmc 0 $LOAD zephyr.bin
echo "Booting Zephyr at $ENTRY..."
dcache flush
dcache off
icache off
go $ENTRY
EOF
    mkimage -A arm -O u-boot -T script -C none -n "$BOARD $sample zephyr boot" \
        -d boot_"$sample".cmd boot.scr

    # Fallback ladder: usbsdmux -> mount a host reader -> an already-mounted dir
    # -> stage files for manual copy. All share _sd_copy; vars come from this
    # function's scope (bash dynamic scoping).
    if [ -n "${SD_MUX:-}" ]; then
        flash_via_mux
    elif [ -n "${SD_PART:-}" ]; then
        flash_via_mount
    elif [ -n "${SD_DIR:-}" ]; then
        flash_via_dir
    else
        flash_manual
    fi

    echo
    info "done. Now: ${RESET_HINT:-reset the board} to boot Zephyr."
    [ -n "${CONSOLE_HINT:-}" ] && info "watch the console: $CONSOLE_HINT"
}

# --- Copy the boot payload into <dir>. $2 is a command prefix ("sudo" or ""). ---
# The PL bitstream must land as system.bit (boot.scr fatloads that name).
_sd_copy() {
    local d=$1 S=${2:-}
    # Preserve the original (PetaLinux) boot.scr once, so it can be restored.
    if [ -f "$d/boot.scr" ] && [ ! -f "$d/boot.scr.linux" ]; then
        $S cp "$d/boot.scr" "$d/boot.scr.linux"
        info "backed up existing boot.scr -> boot.scr.linux"
    fi
    $S cp "$BOOTBIN" "$d/BOOT.BIN"
    [ "$BOOT_CHAIN" = spl ] && $S cp "$UBOOT_IMG" "$d/u-boot.img"
    $S cp "$BIT" "$d/system.bit"
    $S cp "$BIN" "$d/zephyr.bin"
    $S cp boot.scr "$d/boot.scr"
    $S cp boot.scr "$d/boot.scr.$sample"
    sync
}

# --- usbsdmux path: switch card to host, copy, switch back to DUT. ---
flash_via_mux() {
    [ -n "${SD_PART:-}" ] || die "SD_MUX set but SD_PART is empty -- rerun 'zfpga init'"
    sudo usbsdmux "$SD_MUX" host
    sleep 2
    sudo mount "$SD_PART" "$MNT"
    _sd_copy "$MNT" sudo
    sudo umount "$MNT"
    sudo usbsdmux "$SD_MUX" dut
    info "card flashed and switched back to the board (DUT)."
}

# --- No mux, card in a host reader: mount the partition, copy, unmount. ---
flash_via_mount() {
    sudo mount "$SD_PART" "$MNT"
    _sd_copy "$MNT" sudo
    sudo umount "$MNT"
    info "card flashed at $SD_PART -- remove it and put it back in the board."
}

# --- No mux, card already auto-mounted (e.g. /media/you/BOOT): copy in place. ---
flash_via_dir() {
    [ -d "$SD_DIR" ] || die "SD_DIR not a directory: $SD_DIR (is the card mounted?)"
    _sd_copy "$SD_DIR"
    info "card flashed at $SD_DIR -- unmount it, then put it back in the board."
}

# --- Nothing configured: stage files and print manual copy instructions. ---
flash_manual() {
    local out="$WS/build/sdcard"
    rm -rf "$out"; mkdir -p "$out"
    _sd_copy "$out"
    info "no SD target configured -- staged the SD-card files in: $out"
    echo "  Copy ALL files from that folder to your SD card's FAT boot partition,"
    echo "  reinsert the card, then reset the board."
}
